version = 1
; sudo du -h -d 1  /var/lib/docker/.cache/huggingface/hub/

[unsloth/Qwen3.8-27B-GGUF:Q5_K_XL]
ctx-size=145000
temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
fit=off
gpu-layers=all
gpu-layers-draft=all
kv-unified=1
spec-type=draft-mtp
alias=local-vl-qwen27B
;hf=unsloth/Qwen3.8-27B-GGUF:UD-Q5_K_M
no-mmproj-offload=true
threads=8
