services:
  laguna21:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda13-b10257
    container_name: laguna21
    devices:
      - "nvidia.com/gpu=all"
    ports:
      - "8080:8080"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - /var/lib/docker/.cache:/root/.cache:ro
    entrypoint: ["./llama-server"]
    # https://github.com/ggml-org/llama.cpp/tree/master/tools/server
    command: >
      --api-key fursov
      --host 0.0.0.0  --port 8080
      --offline
      --tools all
      --ctx-size 65536
      --model /root/.cache/huggingface/hub/models--unsloth--Laguna-S-2.1-GGUF/snapshots/750f92f90cf54159c4d7a610cb7b3e74498e75c6/UD-Q4_K_XL/Laguna-S-2.1-UD-Q4_K_XL-00001-of-00003.gguf
      --spec-type draft-dflash
      --spec-draft-n-max 15
      --spec-draft-model /root/.cache/huggingface/laguna-s-2.1-DFlash-BF16.gguf
      --fit-target 8192
