version = 1
; sudo du -h -d 1  /var/lib/docker/.cache/huggingface/hub/

[unsloth/medgemma-27b-it-GGUF:Q8_K_XL]
; 31GB
ctx-size=32768

[huihui-ai/Huihui-DeepSeek-V4-Flash-abliterated-GGUF:Q3_K_S]
; du 115 GB
; PP: 68 t/s
; TG: 19 t/s
; MUST be run without tools
ctx-size=16384
