version = 1
; du -h -d 1  /var/lib/docker/.cache/

[unsloth/Qwen3.6-27B-MTP-GGUF:Q5_K_XL]
; du 20 GB
; VRAM: 30.7
; 115 t/s
ctx-size=114688
temp=0.6
top-p=0.95
top-k=20
min-p=0.00
fit=off
gpu-layers=all
gpu-layers-draft=all
kv-unified=1
spec-type=draft-mtp
alias=local-vl-qwen27B
