version = 1
; du -h -d 1  /var/lib/docker/.cache/

[unsloth/medgemma-27b-it-GGUF:Q8_K_XL]
; du 31GB
; nvtop: 43.4 GB
; PP: 2900 t/s
; TG:   24 t/s
ctx-size=131072
fit=off
gpu-layers=all

[unsloth/Qwen3.8-27B-GGUF:Q8_K_XL]
; du 31GB
; Q8 need 2 GPU
ctx-size=260000
fit=off
gpu-layers=all
split-mode=tensor

temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
gpu-layers-draft=all
kv-unified=1
spec-type=draft-mtp
alias=local-vl-qwen27B

[bartowski/orcarouter_Qwen3.8-27B-Uncensored-GGUF:Q5_K_M]
; PP: 2300 t/s
; TG:   77 t/s
; du    21GB
; nvtop 41GB
ctx-size=260000
temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
fit=off
gpu-layers=all
gpu-layers-draft=all
kv-unified=1
spec-type=draft-mtp
;alias=local-vl-qwen27B

[BoldingBuilds/orcarouter_GLM-5.3-Flash-Uncensored-GGUF:IQ3_XXS]
; hf 135GB
; 1x GPU: TG  10 t/s
; 2x GPU: PP 520 t/s
;         TG  15 t/s
ctx-size=65536
no-mmproj=1      
threads=10
batch-size=4096
ubatch-size=4096

[unsloth/Qwen3.8-Flash-Next-GGUF:Q4_K_XL]
; du 106GB
; nvtop 47GB VRAM + 52GB+ RAM
; 1x GPU: PP:  580 t/s
;         TG:   32 t/s

; nvtop 2x 47GB VRAM + 6GB RAM
; 2x GPU: PP: 2100 t/s
;         TG:   63 t/s
ctx-size=200000
batch-size=4096
ubatch-size=4096
temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
threads=10
