version = 1
; du -h -d 1  /var/lib/docker/.cache/

[unsloth/medgemma-27b-it-GGUF:Q8_K_XL]
; du 31GB
; nvtop: 43.4 GB
; TG: 27 t/s
ctx-size=131072
fit=off
gpu-layers=all

[unsloth/Qwen3.8-27B-GGUF:Q8_K_XL]
; du 31GB
ctx-size=260000
temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
fit=off
gpu-layers=all
gpu-layers-draft=all
kv-unified=1
spec-type=draft-mtp
alias=local-vl-qwen27B
;split-mode=tensor

[unsloth/Qwen3.8-Flash-Next-GGUF:Q4_K_XL]
; du 106GB
; nvtop 47GB VRAM + 44GB+ RAM
; PP: 133 t/s
; TG:  33 t/s
ctx-size=131072
temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
threads=10

[bartowski/orcarouter_Qwen3.8-27B-Uncensored-GGUF:Q5_K_M]
ctx-size=260000
temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
fit=off
gpu-layers=all
gpu-layers-draft=all
kv-unified=1
spec-type=draft-mtp
alias=local-vl-qwen27B
